# Kovil — hand-written Makefile with incremental builds.
#
# Each .c compiles to build/*.o; only files whose sources (or included
# headers) changed are recompiled. Header dependencies are generated by
# the compiler itself via -MMD and pulled in with -include below.

CC          := cc
SDL2_CONFIG ?= sdl2-config

CFLAGS  := -std=c99 -Wall -Wextra -Wpedantic -O2 -Iinclude \
           $(shell $(SDL2_CONFIG) --cflags)
LDLIBS  := $(shell $(SDL2_CONFIG) --libs) -lm

SRC := $(wildcard src/*.c)
OBJ := $(SRC:src/%.c=build/%.o)
DEP := $(OBJ:.o=.d)

kovil: $(OBJ)
	$(CC) $(OBJ) -o $@ $(LDLIBS)

build/%.o: src/%.c | build
	$(CC) $(CFLAGS) -MMD -MP -c $< -o $@

build:
	mkdir -p build

-include $(DEP)

# Leak/overflow hunting build: AddressSanitizer reports leaks and
# heap misuse on exit (macOS has no Valgrind; this is the equivalent).
asan: $(SRC)
	$(CC) $(CFLAGS) -g -fsanitize=address,undefined $(SRC) \
	    -o kovil_asan $(LDLIBS)

clean:
	rm -rf build kovil kovil_asan

.PHONY: clean asan
